version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports: 
      - "8080:80"
    environment:
      - NGINX_HOST=dockernode.com
      - NGINX_PORT=80  
    depends_on: 
       - app
  app:
    build: 
      context: ./
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"

networks: 
  node-network:
    driver: bridge    
