apiVersion: apps/v1 
kind: Deployment
metadata:
  name: agendasalaoapi-deployment
  labels:
    app: agendasalaoapi-app
spec:
  selector:
    matchLabels:
      app: agendasalaoapi-app
  replicas: 2
  template:
    metadata: 
      labels:
        app: "agendasalaoapi-app"
    spec:
      containers:
        - name: agendasalaoapi-app
          image: "flavioheartnet/scheduler:v2"
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi  
          envFrom:
            - configMapRef:
                name: scheduler-env
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 1