apiVersion: apps/v1 
kind: Deployment
metadata:
  name: agendasalaoapi-deployment
  labels:
    app: agendasalaoapi-app
spec:
  selector:
    matchLabels:
      app: agendasalaoapi-app
  replicas: 3
  template:
    metadata: 
      labels:
        app: "agendasalaoapi-app"
    spec:
      containers:
        - name: agendasalaoapi-app
          image: "flavioheartnet/scheduler:v2"
          envFrom:
            - configMapRef:
                name: scheduler-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1       
         