apiVersion: v1
kind: Service
metadata:
  name: agendasalaoapi-app-service
spec:
  selector:
    app: agendasalaoapi-app
  type: NodePort  
  ports:
  - port: 3000
    name: agendasalaoapi-app-service
    protocol: TCP
    nodePort: 30001
