name: ci-typescript-workflow
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-application:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run format:analysis
      - run: npm run lint
      - run: npm test:cov
      - run: npm run build
